name: Morning Report

on:
  schedule:
    - cron: '0 22 * * *'  # UTC
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 根据项目需求选择 Python 版本

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Deployment Script
      env:
        ENV_NOTION_TOKEN: ${{ secrets.ENV_NOTION_TOKEN }}
        ENV_DATABASE_ID: ${{ secrets.ENV_DATABASE_ID }}
        ALIBABA_CLOUD_ACCESS_KEY_ID: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
        ALIBABA_CLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
        EMAIL_FROM_ADDRESS: ${{ secrets.EMAIL_FROM_ADDRESS }}
        ALIYUN_REGION: ${{ secrets.ALIYUN_REGION }}
        AI_API_KEY: ${{ secrets.AI_API_KEY }}
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        SKIP_AI: ${{ secrets.SKIP_AI }}
      run: |
        python morning_email.py